-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 03:07:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `bazadedate1` DEFAULT CHARACTER SET utf8 ;


USE `bazadedate1` ;

-- -----------------------------------------------------
-- Table `bazadedate1`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazadedate1`.`course` (
  `course_id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NOT NULL,
  `teacher` VARCHAR(100) NOT NULL,
  `study_year` INT(1) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bazadedate1`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazadedate1`.`students` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bazadedate1`.`enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bazadedate1`.`enrollment` (
  `idenrollment` INT(11) NOT NULL AUTO_INCREMENT,
  `student` INT(11) NOT NULL,
  `curs` INT(11) NOT NULL,
  PRIMARY KEY (`idenrollment`),
  INDEX `student_idx` (`student` ASC),
  INDEX `curs_idx` (`curs` ASC),
  CONSTRAINT `curs`
    FOREIGN KEY (`curs`)
    REFERENCES `bazadedate1`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student`
    FOREIGN KEY (`student`)
    REFERENCES `bazadedate1`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
